### ISSUE TITLE
fix broken links and make original printing instead of red squares

### ISSUE THREAD

**Issue by anastasiabusygina** [NotarizedScreenshot/notaryshot-frontend#112]
![Image](https://user-images.githubusercontent.com/89840876/241003331-1572bf15-6d86-43a2-a09e-642e16a4e324.png)

стрелка на печать неактуальна в этой задаче.

**Comment by poludnev** [comment]
исправил ссылки на деплое, добавил .env с REACT_APP_STORAGE_GATEWAY=https://ipfs.io/ipfs/.

битый шрифт на штампе - проблема бэкенда, сделаю в  другой задаче
