### ISSUE TITLE
Проверить верстку на соответствие макету

### ISSUE THREAD

**Issue by baramba** [NotarizedScreenshot/notaryshot-frontend#28]
Проверить верстку на соответствие макету

**Comment by aleksual** [comment]
1. Разъехалось все, поправить
![2022-07-23_21-07-26](https://user-images.githubusercontent.com/11815733/180617627-1bf689ca-8bfc-4eb3-8a4d-950a1534e977.png)

**Comment by aleksual** [comment]
2. Неправильный заголовок - Profit! нужно
![2022-07-23_21-07-35](https://user-images.githubusercontent.com/11815733/180617645-1c8a88b2-e9b5-4fe1-83b7-4314cd601513.png)

**Comment by aleksual** [comment]
3. Нету иконок, я добавил в фигме
![2022-07-23_21-07-40](https://user-images.githubusercontent.com/11815733/180617670-3a67b4f4-7324-4581-951a-02b385883cca.png)

**Comment by aleksual** [comment]
4. Блок команды сделать как в фигме.
![2022-07-23_21-07-47](https://user-images.githubusercontent.com/11815733/180617701-718fe903-e8f5-437a-af9d-76b57069c68c.png)

**Comment by aleksual** [comment]
5. Этот блок снести нафиг
![2022-07-23_21-07-51](https://user-images.githubusercontent.com/11815733/180617742-954063b7-d77a-43f5-b3ef-da92c5595790.png)

**Comment by aleksual** [comment]
6. нужно поставить в заголовок сайта вот этот текст -  "Quantum Oracle — Save Your Evidence"
сейчас там урл)

**Comment by aleksual** [comment]
7.  Ждем мобильную верстку, этот пункт в приоритете!
