### ISSUE TITLE
Browser plugins

### ISSUE THREAD

**Issue by anastasiabusygina** [NotarizedScreenshot/notaryshot-frontend#67]
https://developer.chrome.com/docs/extensions/mv3/getstarted/ 

- [x] put the extension dev directory in the frontend repo
- [x] add a "Notarize" button for each tweet in the Twitter webpage interface.
- [x] add redirecting to frontend preview page
- [x] maka button to shot current single tweet page
- [x] and an input field for tweet id to be captured

**Comment by poludnev** [comment]
![Image](https://user-images.githubusercontent.com/51874367/226464847-e0b67066-69c3-4aad-8f14-08c99c109168.png)



![Image](https://user-images.githubusercontent.com/51874367/226464911-950f4b1c-bef9-425a-912e-a565b25c603e.png)
