### ISSUE TITLE
Simple version of chrome extension

### ISSUE THREAD

**Issue by Elizavetta** [NotarizedScreenshot/notaryshot-frontend#78]
- [x] create developer chrome extension
- [x] inside extension, create content script for twitter.com, so that we can add elements in twitter UI
- [x] add "Notarize" button in twitter for each tweet block
- [x] add open window(tab) with quantumoracle app, add tweet id to the url params and set url input value constructed from tweet id
- [x] add separate build for extension in notaryshot-frontend app, the result is extension directory, which contains the installation package for extension

**Comment by poludnev** [comment]
![Image](https://user-images.githubusercontent.com/51874367/220986251-7cce3d40-aea9-4dd3-a85e-a0d99f1e1978.png)
